/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Uniformes;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Wdavid
 */
public class InventariodeUniformes extends javax.swing.JDialog {

    /**
     * Creates new form Agenda
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Uniformes> uniformes;
    int aux = 0;

    public InventariodeUniformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtDireccion.setVisible(false);
        txtTelefono.setVisible(false);
        cmbBordado.setVisible(false);
        cmbCuello.setVisible(false);
        cmbEscudo.setVisible(false);
        cmbEstanpado.setVisible(false);
        cmbPuños.setVisible(false);
        cmbTipo.setVisible(false);
        txtNombredeColegio.setVisible(true);
        JButton botonesH[] = {cmdCancelar, cmdBuscar, cmdEliminar};
        JButton botonesD[] = {cmdGuardar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
        ruta = "src/datos/InventariodeUniformes.txt";
        try {
            uniformes = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, uniformes);
        Helper.llenarTablaUniformes(tblTabla1, ruta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombredeColegio = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbBordado = new javax.swing.JComboBox();
        cmbTipo = new javax.swing.JComboBox();
        cmbCuello = new javax.swing.JComboBox();
        cmbPuños = new javax.swing.JComboBox();
        cmbEscudo = new javax.swing.JComboBox();
        cmbEstanpado = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario de Uniformes");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombredeColegio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombredeColegioKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombredeColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, -1));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, -1));

        jLabel1.setText("Telefono");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setText("Nombre del colegio");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Direccion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Cuello");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Escudo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel6.setText("Sexo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        rbMasculino.setBackground(new java.awt.Color(255, 255, 255));
        bgSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");
        jPanel2.add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        rbFemenino.setBackground(new java.awt.Color(255, 255, 255));
        bgSexo.add(rbFemenino);
        rbFemenino.setText("Femenino");
        jPanel2.add(rbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel8.setText("Puños");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel9.setText("Bordado");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setText("Espantado");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel15.setText("Tipo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cmbBordado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jPanel2.add(cmbBordado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diario", "Educacion Fisica" }));
        jPanel2.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));

        cmbCuello.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jPanel2.add(cmbCuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));

        cmbPuños.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jPanel2.add(cmbPuños, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 100, -1));

        cmbEscudo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jPanel2.add(cmbEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, -1));

        cmbEstanpado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jPanel2.add(cmbEstanpado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 480, 230));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setBackground(new java.awt.Color(255, 153, 102));
        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user-symbol.png"))); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        cmdEliminar.setBackground(new java.awt.Color(255, 153, 102));
        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin.png"))); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        cmdCancelar.setBackground(new java.awt.Color(255, 153, 102));
        cmdCancelar.setText("Limpiar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 40));

        cmdBuscar.setBackground(new java.awt.Color(255, 153, 102));
        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier.png"))); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 280, 160));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventario de Uniformes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTabla1.setBackground(new java.awt.Color(204, 255, 255));
        tblTabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        tblTabla1.setForeground(new java.awt.Color(0, 102, 102));
        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre del colegio", "Direccion", "Telefono", "Cuello", "Bordado", "Tipo", "Sexo", "Estanpado", "Escudo", "Puños"
            }
        ));
        tblTabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabla1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1100, 340));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 1120, 370));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo-de-pantalla-Abstracto-229.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1166, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        String nombrecole, direccion, cuello, bordado, tipo, colorcamisa, telefono, estanpado, escudo, puños, colorpùños, colorpantalon, colorcuello, sexo = "";

        nombrecole = txtNombredeColegio.getText();
        direccion = txtDireccion.getText();
        cuello = cmbCuello.getSelectedItem().toString();
        bordado = cmbBordado.getSelectedItem().toString();
        tipo = cmbTipo.getSelectedItem().toString();
        telefono = txtTelefono.getText();
        estanpado = cmbEstanpado.getSelectedItem().toString();
        escudo = cmbEscudo.getSelectedItem().toString();
        puños = cmbPuños.getSelectedItem().toString();

        if (rbFemenino.isSelected()) {
            sexo = sexo + "Femenino";
        } else if (rbMasculino.isSelected()) {
            sexo = sexo + "Masculino";
        }
        if (txtDireccion.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse la direccion del colegio", 1);
        } else if (txtNombredeColegio.getText().trim().isEmpty()) {
            Helper.mensaje(this, "increse el nombre del colegio", aux);
        } else if (txtTelefono.getText().trim().isEmpty()) {
            Helper.mensaje(this, "increse el telefono del colegio", aux);
        } else {
            ArrayList<Uniformes> uniformeModificado;
            try {
                if (aux == 0) {
                    Uniformes u = new Uniformes(nombrecole, direccion, cuello, bordado, tipo, telefono, estanpado, escudo, puños, sexo);
                    u.guardar(salida);
                } else {
                    uniformeModificado = Helper.modificarUniforme(ruta, nombrecole, telefono, cuello, sexo, direccion, tipo, bordado, tipo, escudo, puños);
                    salida = new ObjectOutputStream(new FileOutputStream(ruta));
                    Helper.volcado(salida, uniformeModificado);
                    aux = 0;
                    Helper.mensaje(this, "Uniforme Actualizado Correctamente!", 1);
                }
            } catch (IOException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.llenarTablaUniformes(tblTabla1, ruta);
            txtDireccion.setText("");
            txtNombredeColegio.setText("");
            txtTelefono.setText("");
            cmbBordado.setSelectedItem(0);
            cmbCuello.setSelectedItem(0);
            cmbEscudo.setSelectedItem(0);
            cmbEstanpado.setSelectedItem(0);
            cmbPuños.setSelectedItem(0);
            cmbTipo.setSelectedItem(0);
            bgSexo.clearSelection();
        }
        JButton botonesH[] = {cmdCancelar, cmdBuscar, cmdEliminar};
        JButton botonesD[] = {cmdGuardar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void tblTabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabla1MouseClicked
        int i;
        Uniformes u;
        ArrayList<Uniformes> uniformes = Helper.traerDatos(ruta);
        i = tblTabla1.getSelectedRow();
        u = uniformes.get(i);
        txtDireccion.setText(u.getDireccion());
        txtNombredeColegio.setText(u.getNombredecolegio());
        txtTelefono.setText(u.getTelefono());
        cmbBordado.setSelectedItem(u.getBordado());
        cmbCuello.setSelectedItem(u.getCuello());
        cmbEscudo.setSelectedItem(u.getEscudo());
        cmbEstanpado.setSelectedItem(u.getEstanpado());
        cmbPuños.setSelectedItem(u.getPuños());
        cmbTipo.setSelectedItem(u.getTipo());

        JButton botonesH[] = {cmdCancelar, cmdEliminar};
        JButton botonesD[] = {cmdGuardar, cmdBuscar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_tblTabla1MouseClicked

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        op = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este uniforme del inventario?", "Eliminar", JOptionPane.YES_NO_OPTION);
        ArrayList<Uniformes> uniformes = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {

            i = tblTabla1.getSelectedRow();
            uniformes.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InventariodeUniformes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(InventariodeUniformes.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, uniformes);
            Helper.llenarTablaUniformes(tblTabla1, ruta);

        } else {

        }
        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdEliminar, cmdGuardar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        txtDireccion.setText("");
        txtNombredeColegio.setText("");
        txtTelefono.setText("");
        cmbBordado.setSelectedItem(0);
        cmbCuello.setSelectedItem(0);
        cmbEscudo.setSelectedItem(0);
        cmbEstanpado.setSelectedItem(0);
        cmbPuños.setSelectedItem(0);
        cmbTipo.setSelectedItem(0);
        JButton botonesH[] = {cmdGuardar, cmdBuscar, cmdCancelar, cmdEliminar};
        JButton botonesD[] = {};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String nomcole;
        nomcole = txtNombredeColegio.getText();
        Uniformes u;
        if (Helper.buscarUniforme(nomcole, ruta)) {
            u = Helper.traerUniforme(nomcole, ruta);
            txtNombredeColegio.setText(u.getNombredecolegio());
            txtDireccion.setText(u.getDireccion());
            txtTelefono.setText(u.getTelefono());
            cmbBordado.setSelectedItem(u);
            cmbCuello.setSelectedItem(u);
            cmbEscudo.setSelectedItem(u);
            cmbEstanpado.setSelectedItem(u);
            cmbPuños.setSelectedItem(u);
            cmbTipo.setSelectedItem(u);
            bgSexo.getSelection();
            aux = 1;
        } else {
            txtNombredeColegio.requestFocusInWindow();
            aux = 0;
        }
        txtDireccion.setVisible(true);
        txtTelefono.setVisible(true);
        cmbBordado.setVisible(true);
        cmbCuello.setVisible(true);
        cmbEscudo.setVisible(true);
        cmbEstanpado.setVisible(true);
        cmbPuños.setVisible(true);
        cmbTipo.setVisible(true);
        txtNombredeColegio.setVisible(true);
        JButton botonesH[] = {cmdGuardar, cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void txtNombredeColegioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombredeColegioKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombredeColegioKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventariodeUniformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventariodeUniformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventariodeUniformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventariodeUniformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InventariodeUniformes dialog = new InventariodeUniformes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JComboBox cmbBordado;
    private javax.swing.JComboBox cmbCuello;
    private javax.swing.JComboBox cmbEscudo;
    private javax.swing.JComboBox cmbEstanpado;
    private javax.swing.JComboBox cmbPuños;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tblTabla1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombredeColegio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
