/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.MedidasdeHombre;
import clases.Persona;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Wdavid
 */
public class MedidasdeHombres extends javax.swing.JDialog {

    /**
     * Creates new form Agenda
     */
    String ruta, rutaP;
    ObjectOutputStream salida;
    ArrayList<MedidasdeHombre> MedidasdeHombre;
    int aux = 0;

    public MedidasdeHombres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[] = {cmdLimpiar,  cmdEliminar,cmdNuevo};
        JButton botonesD[] = {cmdModificar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
        ruta = "src/datos/MedidasdeHombre.txt";
        rutaP = "src/datos/Personas.txt";
        Helper.llenarComboPersonasMasculino(cmbPersonas, rutaP);
        try {
            MedidasdeHombre = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, MedidasdeHombre);
        Helper.llenarTablaHombre(tblTabla1, ruta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtPecho = new javax.swing.JTextField();
        txtCintura = new javax.swing.JTextField();
        txtBase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTalleTrasero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTalleDelantero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEspalda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtLargodeManga = new javax.swing.JTextField();
        txtPuños = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLargodePantalon = new javax.swing.JTextField();
        txtLargodeCamisa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAltodeRodilla = new javax.swing.JTextField();
        txtAnchodeRodilla = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAnchodePierna = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtContornoCuello = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cmbPersonas = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdNuevo = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medidas de Hombre");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Medidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPecho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPechoKeyTyped(evt);
            }
        });
        jPanel2.add(txtPecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, -1));

        txtCintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCinturaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, -1));

        txtBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBaseKeyTyped(evt);
            }
        });
        jPanel2.add(txtBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 50, -1));

        jLabel1.setText("Base");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Pecho");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("Cintura");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtTalleTrasero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTalleTraseroKeyTyped(evt);
            }
        });
        jPanel2.add(txtTalleTrasero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, -1));

        jLabel5.setText("Talle Trasero");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtTalleDelantero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTalleDelanteroKeyTyped(evt);
            }
        });
        jPanel2.add(txtTalleDelantero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 50, -1));

        jLabel8.setText("Talle Delantero");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        txtEspalda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspaldaKeyTyped(evt);
            }
        });
        jPanel2.add(txtEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 50, -1));

        jLabel10.setText("Espalda");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel12.setText("Largo de Manga");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        txtLargodeManga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodeMangaKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodeManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 50, -1));

        txtPuños.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuñosKeyTyped(evt);
            }
        });
        jPanel2.add(txtPuños, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, -1));

        jLabel13.setText("Puño");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        txtLargodePantalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodePantalonKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodePantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 50, -1));

        txtLargodeCamisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodeCamisaKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodeCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 50, -1));

        jLabel14.setText("Largo de Camisa");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel15.setText("Largo de Pantalon");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel16.setText("Alto de Rodilla");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        txtAltodeRodilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltodeRodillaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAltodeRodilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 50, -1));

        txtAnchodeRodilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchodeRodillaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAnchodeRodilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 50, -1));

        jLabel19.setText("Ancho de Rodilla");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        txtAnchodePierna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchodePiernaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAnchodePierna, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 50, -1));

        jLabel20.setText("Ancho de Pierna");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        txtContornoCuello.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContornoCuelloKeyTyped(evt);
            }
        });
        jPanel2.add(txtContornoCuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 50, -1));

        jLabel21.setText("Contorno de cuello");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jPanel2.add(cmbPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 470, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 630, 230));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdNuevo.setBackground(new java.awt.Color(153, 153, 153));
        cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fountain-pen-close-up.png"))); // NOI18N
        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        cmdEliminar.setBackground(new java.awt.Color(153, 153, 153));
        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin.png"))); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        cmdLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 40));

        cmdModificar.setBackground(new java.awt.Color(153, 153, 153));
        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 280, 160));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medidas de Hombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTabla1.setBackground(new java.awt.Color(204, 255, 255));
        tblTabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        tblTabla1.setForeground(new java.awt.Color(0, 102, 102));
        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Talle Delantero", "Talle Trasero", "Pecho", "Cintura", "Base", "Espalda", "Largo de Manga", "Puño", "Largo de Pantalon", "Alto de Rodilla", "Ancho de Rodilla", "Ancho de Pierna", "Contorno de Cuello", "Largo de Camisa"
            }
        ));
        tblTabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabla1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 1160, 390));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1180, 420));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos  .jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1236, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed

        String talletra, talledela, pecho, altorodi, anchopier, espalda, anchoderodi, cintura, base, largodepanta,
                largodemanga, puno, largodecamisa, contorcuello, auxPersona, celular;
        int indice;
        Persona personas;
        talletra = txtTalleTrasero.getText();
        talledela = txtTalleDelantero.getText();
        pecho = txtPecho.getText();
        cintura = txtCintura.getText();
        base = txtBase.getText();
        espalda = txtEspalda.getText();
        altorodi = txtAltodeRodilla.getText();
        anchopier = txtAnchodePierna.getText();
        anchoderodi = txtAnchodeRodilla.getText();
        largodepanta = txtLargodePantalon.getText();
        largodemanga = txtLargodeManga.getText();
        puno = txtPuños.getText();
        largodecamisa = txtLargodeCamisa.getText();
        contorcuello = txtContornoCuello.getText();

        auxPersona = cmbPersonas.getSelectedItem().toString();
        indice = auxPersona.indexOf("-") - 1;
        celular = auxPersona.substring(0, indice);
        ArrayList<MedidasdeHombre> medidasModificado;
        personas = Helper.traerPersonaCelular(celular, rutaP);
        if (txtAltodeRodilla.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de alto de rodilla ", 1);
            txtAltodeRodilla.requestFocusInWindow();
        } else if (txtAnchodePierna.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de ancho de pierna ", 1);
            txtAnchodePierna.requestFocusInWindow();
        } else if (txtAnchodeRodilla.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de ancho de rodilla ", 1);
            txtAnchodeRodilla.requestFocusInWindow();
        } else if (txtBase.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de la base ", 1);
            txtBase.requestFocusInWindow();
        } else if (txtCintura.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de la cintura ", 1);
            txtCintura.requestFocusInWindow();
        } else if (txtContornoCuello.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del contorno del cuello ", 1);
            txtContornoCuello.requestFocusInWindow();
        } else if (txtEspalda.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de espalda ", 1);
            txtEspalda.requestFocusInWindow();
        } else if (txtLargodeCamisa.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del largo de camisa ", 1);
            txtLargodeCamisa.requestFocusInWindow();
        } else if (txtLargodeManga.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del largo de manga ", 1);
            txtLargodeManga.requestFocusInWindow();
        } else if (txtLargodePantalon.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de largo de pantalon ", 1);
            txtLargodePantalon.requestFocusInWindow();
        } else if (txtPecho.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del pecho ", 1);
            txtPecho.requestFocusInWindow();
        } else if (txtPuños.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de los puños ", 1);
            txtPuños.requestFocusInWindow();
        } else if (txtTalleDelantero.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del talle delantero ", 1);
            txtTalleDelantero.requestFocusInWindow();
        } else if (txtTalleTrasero.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del talle trasero ", 1);
            txtTalleTrasero.requestFocusInWindow();
        } else {
            try {
                if (aux == 0) {
                    MedidasdeHombre m = new MedidasdeHombre(talletra, talledela, pecho, altorodi, anchopier, espalda, anchoderodi, cintura, base, largodepanta, largodemanga, puno, largodecamisa, contorcuello, personas);
                    m.guardar(salida);
                } else {
                    medidasModificado = Helper.modificarMedidasdeHombre(ruta, talletra, talledela, pecho, altorodi, anchopier, espalda, anchoderodi, cintura, base, largodepanta, largodemanga, puno, largodecamisa, contorcuello);
                    salida = new ObjectOutputStream(new FileOutputStream(rutaP));
                    Helper.volcado(salida, medidasModificado);
                    aux = 0;
                    Helper.mensaje(this, "Medidas Actualizado Correctamente", 1);
                }

            } catch (IOException ex) {
                Logger.getLogger(MedidasdeHombres.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.llenarTablaHombre(tblTabla1, ruta);
            txtAltodeRodilla.setText("");
            txtAnchodePierna.setText("");
            txtAnchodeRodilla.setText("");
            txtPecho.setText("");
            txtBase.setText("");
            txtCintura.setText("");
            txtEspalda.setText("");
            txtLargodeCamisa.setText("");
            txtLargodeManga.setText("");
            txtLargodePantalon.setText("");
            cmbPersonas.setSelectedIndex(0);
            txtTalleDelantero.setText("");
            txtPuños.setText("");
            txtTalleTrasero.setText("");
            txtContornoCuello.setText("");

        }//llenarTabla}
        JButton botonesH[] = {cmdLimpiar, cmdModificar, cmdEliminar};
        JButton botonesD[] = {cmdNuevo};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void tblTabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabla1MouseClicked

        int i;
        MedidasdeHombre m;
        ArrayList<MedidasdeHombre> Medidasdehombres = Helper.traerDatos(ruta);
        i = tblTabla1.getSelectedRow();
        m = MedidasdeHombre.get(i);

        txtAltodeRodilla.setText(m.getAltodeRodilla());
        txtAnchodePierna.setText(m.getAnchodepierna());
        txtAnchodeRodilla.setText(m.getAltodeRodilla());
        txtBase.setText(m.getBase());
        txtCintura.setText(m.getCintura());
        txtContornoCuello.setText(m.getContoronodeCuello());
        txtEspalda.setText(m.getEspalda());
        txtLargodeCamisa.setText(m.getLargodeCamisa());
        txtLargodeManga.setText(m.getLargodeManga());
        txtLargodePantalon.setText(m.getLargodePantalon());
        txtPecho.setText(m.getPecho());
        txtPuños.setText(m.getPuño());
        txtTalleDelantero.setText(m.getTalleDelantero());
        txtTalleTrasero.setText(m.getTalleTrasero());

        JButton botonesH[] = {cmdLimpiar, cmdEliminar};
        JButton botonesD[] = {cmdNuevo, cmdModificar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_tblTabla1MouseClicked

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        op = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar las medidas de esta persona?", "Eliminar", JOptionPane.YES_NO_OPTION);
        ArrayList<MedidasdeHombre> Medidasdehombres = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {

            i = tblTabla1.getSelectedRow();
            MedidasdeHombre.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MedidasdeHombre.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MedidasdeHombre.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, MedidasdeHombre);
            Helper.llenarTablaHombre(tblTabla1, ruta);

            cmbPersonas.setSelectedIndex(0);
            txtTalleTrasero.setText("");
            txtPecho.setText("");
            txtCintura.setText("");
            txtBase.setText("");

        } else {

        }
        JButton botonesH[] = {cmdModificar, cmdLimpiar};
        JButton botonesD[] = {cmdEliminar, cmdNuevo};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtAltodeRodilla.setText("");
        txtAnchodePierna.setText("");
        txtAnchodeRodilla.setText("");
        txtPecho.setText("");
        txtBase.setText("");
        txtCintura.setText("");
        txtEspalda.setText("");
        txtLargodeCamisa.setText("");
        txtLargodeManga.setText("");
        txtLargodePantalon.setText("");
        cmbPersonas.setSelectedIndex(0);
        txtTalleDelantero.setText("");
        txtPuños.setText("");
        txtTalleTrasero.setText("");
        txtContornoCuello.setText("");
        
        JButton botonesH[] = {cmdNuevo, cmdModificar, cmdLimpiar, cmdEliminar};
        JButton botonesD[] = {};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        //Modificador
        String espalda, auxPersonas;
        Persona personas;
        espalda = txtEspalda.getText();
        MedidasdeHombre m;
        if (Helper.buscarMedidasdeHombre(espalda, ruta)) {
            m = Helper.traerMedidasdeHombre(espalda, ruta);
            txtEspalda.setText(m.getEspalda());
            personas = m.getPersonas();
            auxPersonas = personas.getCelular() + " - " + personas.getNombre() + "  " + personas.getApellidos() + " - " + personas.getDireccion() + " - " + personas.getSexo() + " - " + personas.getTelefono();
            cmbPersonas.setSelectedItem(auxPersonas);
            aux = 1;
        } else {
            txtEspalda.requestFocusInWindow();
            aux = 0;
        }
        JButton botonesH[] = {cmdNuevo, cmdModificar, cmdLimpiar};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void txtEspaldaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspaldaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaldaKeyTyped

    private void txtTalleTraseroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTalleTraseroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTalleTraseroKeyTyped

    private void txtPechoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPechoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPechoKeyTyped

    private void txtCinturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCinturaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinturaKeyTyped

    private void txtBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaseKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseKeyTyped

    private void txtTalleDelanteroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTalleDelanteroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTalleDelanteroKeyTyped

    private void txtLargodeMangaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodeMangaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodeMangaKeyTyped

    private void txtPuñosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuñosKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuñosKeyTyped

    private void txtLargodePantalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodePantalonKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodePantalonKeyTyped

    private void txtAltodeRodillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltodeRodillaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltodeRodillaKeyTyped

    private void txtAnchodeRodillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchodeRodillaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnchodeRodillaKeyTyped

    private void txtAnchodePiernaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchodePiernaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnchodePiernaKeyTyped

    private void txtContornoCuelloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContornoCuelloKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtContornoCuelloKeyTyped

    private void txtLargodeCamisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodeCamisaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodeCamisaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasdeHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasdeHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasdeHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasdeHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedidasdeHombres dialog = new MedidasdeHombres(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JComboBox cmbPersonas;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla1;
    private javax.swing.JTextField txtAltodeRodilla;
    private javax.swing.JTextField txtAnchodePierna;
    private javax.swing.JTextField txtAnchodeRodilla;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtCintura;
    private javax.swing.JTextField txtContornoCuello;
    private javax.swing.JTextField txtEspalda;
    private javax.swing.JTextField txtLargodeCamisa;
    private javax.swing.JTextField txtLargodeManga;
    private javax.swing.JTextField txtLargodePantalon;
    private javax.swing.JTextField txtPecho;
    private javax.swing.JTextField txtPuños;
    private javax.swing.JTextField txtTalleDelantero;
    private javax.swing.JTextField txtTalleTrasero;
    // End of variables declaration//GEN-END:variables
}
