/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.MedidasdeMujer;
import clases.Persona;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Wdavid
 */
public class MedidasdeMujeres extends javax.swing.JDialog {

    /**
     * Creates new form Agenda
     */
    String ruta, rutaP;
    ObjectOutputStream salida;
    ArrayList<MedidasdeMujeres> Medidasdemujer;
    int aux = 0;

    public MedidasdeMujeres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[] = {cmdNuevo, cmdLimpiar, cmdEliminar};
        JButton botonesD[] = {cmdModificar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
        ruta = "src/datos/MedidasdeMujer.txt";
        rutaP = "src/datos/Personas.txt";
        Helper.llenarComboPersonasFemenino(cmbPersonas, rutaP);
        try {
            Medidasdemujer = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, Medidasdemujer);
        Helper.llenarTablaMujeres(tblTabla1, ruta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtBusto = new javax.swing.JTextField();
        txtCintura = new javax.swing.JTextField();
        txtCadera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTalleTrasero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTalleDelantero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAltodePinza = new javax.swing.JTextField();
        txtEspalda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSeparaciondePinza = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLargodeManga = new javax.swing.JTextField();
        txtPuño = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLargodePantalon = new javax.swing.JTextField();
        txtLargodeFalda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAltodeRodilla = new javax.swing.JTextField();
        txtAnchodeRodilla = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAnchodePierna = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cmbPersonas = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdNuevo = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medidas de Mujer");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Medidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBustoKeyTyped(evt);
            }
        });
        jPanel2.add(txtBusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, -1));

        txtCintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCinturaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 50, -1));

        txtCadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCaderaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 50, -1));

        jLabel1.setText("Cadera");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Busto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setText("Cintura");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtTalleTrasero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTalleTraseroKeyTyped(evt);
            }
        });
        jPanel2.add(txtTalleTrasero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, -1));

        jLabel5.setText("Talle Trasero");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtTalleDelantero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTalleDelanteroKeyTyped(evt);
            }
        });
        jPanel2.add(txtTalleDelantero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, -1));

        jLabel8.setText("Talle Delantero");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel9.setText("Alto de Pinza");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        txtAltodePinza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltodePinzaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAltodePinza, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, -1));

        txtEspalda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspaldaKeyTyped(evt);
            }
        });
        jPanel2.add(txtEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 50, -1));

        jLabel10.setText("Espalda");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel11.setText("Separacion de Pinza");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, -1));

        txtSeparaciondePinza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeparaciondePinzaKeyTyped(evt);
            }
        });
        jPanel2.add(txtSeparaciondePinza, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 50, -1));

        jLabel12.setText("Lago de Manga");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        txtLargodeManga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodeMangaKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodeManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 50, -1));

        txtPuño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuñoKeyTyped(evt);
            }
        });
        jPanel2.add(txtPuño, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 50, -1));

        jLabel13.setText("Puño");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        txtLargodePantalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodePantalonKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodePantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 50, -1));

        txtLargodeFalda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargodeFaldaKeyTyped(evt);
            }
        });
        jPanel2.add(txtLargodeFalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 50, -1));

        jLabel14.setText("Largo de Falda");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel15.setText("Largo de Pantalon");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel16.setText("Alto de Rodilla");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        txtAltodeRodilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltodeRodillaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAltodeRodilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 50, -1));

        txtAnchodeRodilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchodeRodillaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAnchodeRodilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 50, -1));

        jLabel19.setText("Ancho de Rodilla");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        txtAnchodePierna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchodePiernaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAnchodePierna, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, -1));

        jLabel20.setText("Ancho de Pierna");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        cmbPersonas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(cmbPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 430, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 590, 230));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdNuevo.setBackground(new java.awt.Color(153, 153, 153));
        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        cmdEliminar.setBackground(new java.awt.Color(153, 153, 153));
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        cmdLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 40));

        cmdModificar.setBackground(new java.awt.Color(153, 153, 153));
        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 280, 160));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medidas de Mujer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTabla1.setBackground(new java.awt.Color(204, 255, 255));
        tblTabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        tblTabla1.setForeground(new java.awt.Color(0, 102, 102));
        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Espalda", "Talle Trasero", "Talle Delantero", "Busto", "Alto de Rodilla", "Ancho de Pierna", "Alto de Pinza", "Separacion de Pinza", "Ancho de Rodilla", "Cintura", "Cadera", "Largo de Pantalon", "Largo de manga", "Puño", "Largo de Falda"
            }
        ));
        tblTabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabla1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 1160, 390));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1180, 420));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos  .jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1236, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed

        String nom, talletra, talledela, busto, altorodi, anchopier, espalda, altodepinza, separaciondepin, anchoderodi, cintura, cadera, largodepanta,
                largodemanga, puno, largodefalda, auxPersona, celular;
        int indice;
        Persona personas;
        talletra = txtTalleTrasero.getText();
        talledela = txtTalleDelantero.getText();
        busto = txtBusto.getText();
        cintura = txtCintura.getText();
        cadera = txtCadera.getText();
        largodepanta = txtLargodePantalon.getText();
        altorodi = txtAltodeRodilla.getText();
        anchoderodi = txtAnchodeRodilla.getText();
        anchopier = txtAnchodePierna.getText();
        espalda = txtEspalda.getText();
        altodepinza = txtAltodePinza.getText();
        separaciondepin = txtSeparaciondePinza.getText();
        largodemanga = txtLargodeManga.getText();
        puno = txtPuño.getText();
        largodefalda = txtLargodeFalda.getText();
        auxPersona = cmbPersonas.getSelectedItem().toString();
        indice = auxPersona.indexOf("-") - 1;
        celular = auxPersona.substring(0, indice);
        ArrayList<MedidasdeMujer> medidasModificado;
        personas = Helper.traerPersonaCelular(celular, rutaP);
        if (txtAltodeRodilla.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de alto de rodilla ", 1);
            txtAltodeRodilla.requestFocusInWindow();
        } else if (txtAnchodePierna.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de ancho de pierna ", 1);
            txtAnchodePierna.requestFocusInWindow();
        } else if (txtAnchodeRodilla.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de ancho de rodilla ", 1);
            txtAnchodeRodilla.requestFocusInWindow();
        } else if (txtBusto.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del busto ", 1);
            txtBusto.requestFocusInWindow();
        } else if (txtCintura.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de la cintura ", 1);
            txtCintura.requestFocusInWindow();
        } else if (txtEspalda.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de espalda ", 1);
            txtEspalda.requestFocusInWindow();
        } else if (txtLargodeFalda.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del largo de la falda ", 1);
            txtLargodeFalda.requestFocusInWindow();
        } else if (txtLargodeManga.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del largo de manga ", 1);
            txtLargodeManga.requestFocusInWindow();
        } else if (txtLargodePantalon.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de largo de pantalon ", 1);
            txtLargodePantalon.requestFocusInWindow();
        } else if (txtCadera.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de la cadera ", 1);
            txtCadera.requestFocusInWindow();
        } else if (txtPuño.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de los puños ", 1);
            txtPuño.requestFocusInWindow();
        } else if (txtTalleDelantero.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del talle delantero ", 1);
            txtTalleDelantero.requestFocusInWindow();
        } else if (txtTalleTrasero.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del talle trasero ", 1);
            txtTalleTrasero.requestFocusInWindow();
        } else if (txtSeparaciondePinza.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad de la separacion de pinza ", 1);
            txtSeparaciondePinza.requestFocusInWindow();
        } else if (txtAltodePinza.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Increse por favor la medidad del alto de pinza ", 1);
            txtAltodePinza.requestFocusInWindow();
        } else {

            try {
                if (aux == 0) {
                    MedidasdeMujer m = new MedidasdeMujer(talletra, talledela, busto, cintura, cadera, espalda, altorodi, anchopier, altodepinza, separaciondepin, anchoderodi, largodepanta, largodemanga, puno, largodefalda, personas);
                    m.guardar(salida);

                } else {
                    medidasModificado = Helper.modificarMedidasdeMujer(ruta, talletra, talledela, busto, altorodi, anchopier, espalda, altodepinza, separaciondepin, anchoderodi, cintura, cadera, largodepanta, largodemanga, puno, largodefalda);
                    salida = new ObjectOutputStream(new FileOutputStream(rutaP));
                    Helper.volcado(salida, medidasModificado);
                    aux = 0;
                    Helper.mensaje(this, "Medidas Actualizado Correctamente", 1);
                }

            } catch (IOException ex) {
                Logger.getLogger(MedidasdeMujeres.class.getName()).log(Level.SEVERE, null, ex);
            }

            Helper.llenarTablaMujeres(tblTabla1, ruta);
            txtAltodePinza.setText("");
            txtAltodeRodilla.setText("");
            txtAnchodePierna.setText("");
            txtAnchodeRodilla.setText("");
            txtBusto.setText("");
            txtCadera.setText("");
            txtCintura.setText("");
            txtEspalda.setText("");
            txtLargodeFalda.setText("");
            txtLargodeManga.setText("");
            txtLargodePantalon.setText("");
            cmbPersonas.setSelectedIndex(0);
            txtSeparaciondePinza.setText("");
            txtTalleDelantero.setText("");
            txtPuño.setText("");
            txtTalleTrasero.setText("");

            txtEspalda.requestFocusInWindow();
        }
        JButton botonesH[] = {cmdLimpiar, cmdModificar, cmdEliminar};
        JButton botonesD[] = {cmdNuevo};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void tblTabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabla1MouseClicked
        int i;
        MedidasdeMujer m;
        ArrayList<MedidasdeMujer> Medidasdemujer = Helper.traerDatos(ruta);
        i = tblTabla1.getSelectedRow();
        m = Medidasdemujer.get(i);

        txtAltodeRodilla.setText(m.getAltodeRodilla());
        txtAnchodePierna.setText(m.getAnchodepierna());
        txtAnchodeRodilla.setText(m.getAltodeRodilla());
        txtCadera.setText(m.getCadera());
        txtCintura.setText(m.getCintura());
        //txtContornoCuello.setText(m.getContoronodeCuello());
        txtEspalda.setText(m.getEspalda());
        txtLargodeFalda.setText(m.getLargodeFalda());
        txtLargodeManga.setText(m.getLargodeManga());
        txtLargodePantalon.setText(m.getLargodePantalon());
        txtBusto.setText(m.getBusto());
        txtPuño.setText(m.getPuño());
        txtTalleDelantero.setText(m.getTalleDelantero());
        txtTalleTrasero.setText(m.getTalleTrasero());
        txtAltodePinza.setText(m.getAltodePinza());
        txtSeparaciondePinza.setText(m.getSeparaciondePinza());
                
        
        JButton botonesH[] = {cmdLimpiar, cmdEliminar, cmdModificar};
        JButton botonesD[] = {cmdNuevo};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_tblTabla1MouseClicked

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        op = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar las medidas de esta persona?", "Eliminar", JOptionPane.YES_NO_OPTION);
        ArrayList<MedidasdeMujeres> Medidasdemujer = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {

            i = tblTabla1.getSelectedRow();
            Medidasdemujer.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MedidasdeMujeres.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MedidasdeMujeres.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, Medidasdemujer);
            Helper.llenarTablaMujeres(tblTabla1, ruta);

            cmbPersonas.setSelectedIndex(0);
            txtTalleTrasero.setText("");
            txtBusto.setText("");
            txtCintura.setText("");
            txtCadera.setText("");
            txtEspalda.requestFocusInWindow();
        } else {

        }
        JButton botonesH[] = {cmdModificar, cmdLimpiar, cmdNuevo};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtAltodePinza.setText("");
        txtAltodeRodilla.setText("");
        txtAnchodePierna.setText("");
        txtAnchodeRodilla.setText("");
        txtBusto.setText("");
        txtCadera.setText("");
        txtCintura.setText("");
        txtEspalda.setText("");
        txtLargodeFalda.setText("");
        txtLargodeManga.setText("");
        txtLargodePantalon.setText("");
        cmbPersonas.setSelectedIndex(0);
        txtSeparaciondePinza.setText("");
        txtTalleDelantero.setText("");
        txtPuño.setText("");
        txtTalleTrasero.setText("");
        txtEspalda.requestFocusInWindow();
        JButton botonesH[] = {cmdNuevo, cmdModificar, cmdLimpiar, cmdEliminar};
        JButton botonesD[] = {};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        String espalda, auxPersonas;
        Persona personas;
        espalda = txtEspalda.getText();
        MedidasdeMujer m;
        if (Helper.buscarMedidasdeMujer(espalda, ruta)) {
            m = Helper.traerMedidasdeMujer(espalda, ruta);
            txtEspalda.setText(m.getEspalda());
            personas = m.getPersonas();
            auxPersonas = personas.getCelular() + " - " + personas.getNombre() + "  " + personas.getApellidos() + " - " + personas.getDireccion() + " - " + personas.getSexo() + " - " + personas.getTelefono();
            cmbPersonas.setSelectedItem(auxPersonas);
            aux = 1;
        } else {
            txtEspalda.requestFocusInWindow();
            aux = 0;
        }
        JButton botonesH[] = {cmdNuevo, cmdModificar, cmdLimpiar};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotonoes(botonesH);
        Helper.deshabilitarBotonoes(botonesD);
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void txtEspaldaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspaldaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaldaKeyTyped

    private void txtTalleTraseroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTalleTraseroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTalleTraseroKeyTyped

    private void txtTalleDelanteroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTalleDelanteroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTalleDelanteroKeyTyped

    private void txtBustoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBustoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtBustoKeyTyped

    private void txtCinturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCinturaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinturaKeyTyped

    private void txtCaderaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaderaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaderaKeyTyped

    private void txtLargodePantalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodePantalonKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodePantalonKeyTyped

    private void txtAltodeRodillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltodeRodillaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltodeRodillaKeyTyped

    private void txtAnchodeRodillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchodeRodillaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnchodeRodillaKeyTyped

    private void txtAnchodePiernaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchodePiernaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnchodePiernaKeyTyped

    private void txtAltodePinzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltodePinzaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltodePinzaKeyTyped

    private void txtSeparaciondePinzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeparaciondePinzaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeparaciondePinzaKeyTyped

    private void txtLargodeMangaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodeMangaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodeMangaKeyTyped

    private void txtPuñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuñoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuñoKeyTyped

    private void txtLargodeFaldaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargodeFaldaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargodeFaldaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasdeMujeres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasdeMujeres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasdeMujeres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasdeMujeres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedidasdeMujeres dialog = new MedidasdeMujeres(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JComboBox cmbPersonas;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla1;
    private javax.swing.JTextField txtAltodePinza;
    private javax.swing.JTextField txtAltodeRodilla;
    private javax.swing.JTextField txtAnchodePierna;
    private javax.swing.JTextField txtAnchodeRodilla;
    private javax.swing.JTextField txtBusto;
    private javax.swing.JTextField txtCadera;
    private javax.swing.JTextField txtCintura;
    private javax.swing.JTextField txtEspalda;
    private javax.swing.JTextField txtLargodeFalda;
    private javax.swing.JTextField txtLargodeManga;
    private javax.swing.JTextField txtLargodePantalon;
    private javax.swing.JTextField txtPuño;
    private javax.swing.JTextField txtSeparaciondePinza;
    private javax.swing.JTextField txtTalleDelantero;
    private javax.swing.JTextField txtTalleTrasero;
    // End of variables declaration//GEN-END:variables
}
