/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;

/**
 *
 * @author Wdavid
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    String ruta , rutaC , rutaT, rutaU ,rutaMH , rutaMJ;
    
    public Principal() {
        initComponents();
        ruta = "src/datos/personas.txt";
        rutaC = "src/datos/Cliente.txt";
        rutaT = "src/datos/InventariodeTogas.bin";
        rutaU = "src/datos/InventariodeUniformes.txt";
        rutaMH = "src/datos/MedidasdeHombre.txt";
        rutaMJ = "src/datos/MedidasdeMujer.txt";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        mnAgenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnCantdePersonas = new javax.swing.JMenuItem();
        mnCantdeTogas = new javax.swing.JMenuItem();
        mnCantdeUniformes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        mnInventarios = new javax.swing.JMenu();
        mnInventarioUniformes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnInventarioTogas = new javax.swing.JMenuItem();
        mnMedidas = new javax.swing.JMenu();
        mnMedidasdeMujer = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnMedidasHombre = new javax.swing.JMenuItem();
        mnAlquiler = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confecciones Maribel");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdSalir.setBackground(new java.awt.Color(51, 153, 255));
        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/power.png"))); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta 2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 510, 630));

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 204));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));
        jMenuBar1.setFocusTraversalPolicyProvider(true);

        mnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanical-gears-.png"))); // NOI18N
        mnOpciones.setText("Opciones");

        mnAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notebook-of-contacts.png"))); // NOI18N
        mnAgenda.setText("Agenda");
        mnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgendaActionPerformed(evt);
            }
        });
        mnOpciones.add(mnAgenda);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eye.png"))); // NOI18N
        jMenu2.setText("Reportes");

        jMenu4.setText("Cantidades");

        mnCantdePersonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnCantdePersonas.setText("Cantidad de Personas en la Agenda");
        mnCantdePersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantdePersonasActionPerformed(evt);
            }
        });
        jMenu4.add(mnCantdePersonas);

        mnCantdeTogas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnCantdeTogas.setText("Cantidad de Togas");
        mnCantdeTogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantdeTogasActionPerformed(evt);
            }
        });
        jMenu4.add(mnCantdeTogas);

        mnCantdeUniformes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnCantdeUniformes.setText("Cantidad de Uniformes ");
        mnCantdeUniformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantdeUniformesActionPerformed(evt);
            }
        });
        jMenu4.add(mnCantdeUniformes);

        jMenu2.add(jMenu4);

        jMenu5.setText("Listado");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("LIstadoCompleto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenu2.add(jMenu5);

        mnOpciones.add(jMenu2);
        mnOpciones.add(jSeparator1);

        mnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/power.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        mnInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/old-fashion-briefcase.png"))); // NOI18N
        mnInventarios.setText("Inventarios");

        mnInventarioUniformes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnInventarioUniformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t-shirt-of-soccer-player-front.png"))); // NOI18N
        mnInventarioUniformes.setText("Inventario de Uniformes");
        mnInventarioUniformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInventarioUniformesActionPerformed(evt);
            }
        });
        mnInventarios.add(mnInventarioUniformes);
        mnInventarios.add(jSeparator2);

        mnInventarioTogas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnInventarioTogas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/graduation-hat.png"))); // NOI18N
        mnInventarioTogas.setText("Inventario de Togas");
        mnInventarioTogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInventarioTogasActionPerformed(evt);
            }
        });
        mnInventarios.add(mnInventarioTogas);

        jMenuBar1.add(mnInventarios);

        mnMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/female-and-male-silhouettes-with-a-vertical-line-in-the-middle.png"))); // NOI18N
        mnMedidas.setText("Mediadas");
        mnMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMedidasActionPerformed(evt);
            }
        });

        mnMedidasdeMujer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnMedidasdeMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/businesswoman.png"))); // NOI18N
        mnMedidasdeMujer.setText("Medidas de Mujer");
        mnMedidasdeMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMedidasdeMujerActionPerformed(evt);
            }
        });
        mnMedidas.add(mnMedidasdeMujer);
        mnMedidas.add(jSeparator5);

        mnMedidasHombre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mnMedidasHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/businessman.png"))); // NOI18N
        mnMedidasHombre.setText("Medidas de Hombre");
        mnMedidasHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMedidasHombreActionPerformed(evt);
            }
        });
        mnMedidas.add(mnMedidasHombre);

        jMenuBar1.add(mnMedidas);

        mnAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/list.png"))); // NOI18N
        mnAlquiler.setText("Alquilar");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Alquier");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/partnership.png"))); // NOI18N
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        mnAlquiler.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mnAlquiler);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(494, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgendaActionPerformed
        Agenda a = new Agenda(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnAgendaActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnMedidasdeMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMedidasdeMujerActionPerformed
        MedidasdeMujeres m = new MedidasdeMujeres(this, true);
        m.setVisible(true);
    }//GEN-LAST:event_mnMedidasdeMujerActionPerformed

    private void mnMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMedidasActionPerformed
        //Error
    }//GEN-LAST:event_mnMedidasActionPerformed

    private void mnMedidasHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMedidasHombreActionPerformed
        MedidasdeHombres h = new MedidasdeHombres(this, true);
        h.setVisible(true);
    }//GEN-LAST:event_mnMedidasHombreActionPerformed

    private void mnInventarioUniformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInventarioUniformesActionPerformed
        InventariodeUniformes u = new InventariodeUniformes(this, true);
        u.setVisible(true);
    }//GEN-LAST:event_mnInventarioUniformesActionPerformed

    private void mnInventarioTogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInventarioTogasActionPerformed
        InventariodeTogas t = new InventariodeTogas(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_mnInventarioTogasActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
       Alquilar2 a = new Alquilar2 (this, true);
       a.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void mnCantdePersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantdePersonasActionPerformed
        int cont;
        cont = Helper.traerDatos(ruta).size();
        Helper.mensaje(this, "El numero de personas en la agenda es : "+cont, 1);
    }//GEN-LAST:event_mnCantdePersonasActionPerformed

    private void mnCantdeTogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantdeTogasActionPerformed
        int cont;
        cont = Helper.traerDatos(rutaT).size();
        Helper.mensaje(this, "El numero de togas en el inventario es : "+cont, 1);
    }//GEN-LAST:event_mnCantdeTogasActionPerformed

    private void mnCantdeUniformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantdeUniformesActionPerformed
        int cont;
        cont = Helper.traerDatos(rutaU).size();
        Helper.mensaje(this, "El numero de uniformes en el inventario es : "+cont, 1);
    }//GEN-LAST:event_mnCantdeUniformesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ListadoCompletodePersonas l = new ListadoCompletodePersonas (this , true);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSalir;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem mnAgenda;
    private javax.swing.JMenu mnAlquiler;
    private javax.swing.JMenuItem mnCantdePersonas;
    private javax.swing.JMenuItem mnCantdeTogas;
    private javax.swing.JMenuItem mnCantdeUniformes;
    private javax.swing.JMenuItem mnInventarioTogas;
    private javax.swing.JMenuItem mnInventarioUniformes;
    private javax.swing.JMenu mnInventarios;
    private javax.swing.JMenu mnMedidas;
    private javax.swing.JMenuItem mnMedidasHombre;
    private javax.swing.JMenuItem mnMedidasdeMujer;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables
}
